Repository mgierlasinski/MagicGradients, pull requests merged in 2019-10, with the labels that each got.

#17 Updated Readme to include Getting Started
  README.md
Labels: documentation, enhancement

#16 Correct Packages Information
  README.md
Labels: bug, documentation

#19 [Enhancement] Refactor codebase
  MagicGradients.Benchmark/Program.cs
  MagicGradients.Tests/MagicGradients.Tests.csproj
  MagicGradients.Tests/Parser/CssGradientParserTests.cs
  MagicGradients.Tests/Parser/CssGradientParserTestsData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorChannelDefinitionTests.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorHexDefinitionTests.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorNameDefinitionTests.cs
  MagicGradients/CssGradientSource.cs
  MagicGradients/Gradient.cs
  MagicGradients/GradientBuilder.cs
  MagicGradients/GradientSource.cs
  MagicGradients/GradientStop.cs
  MagicGradients/GradientView.cs
  MagicGradients/IGradientSource.cs
  MagicGradients/LinearGradient.cs
  MagicGradients/LinearGradientSource.cs
  MagicGradients/LinearGradientView.cs
  MagicGradients/MagicGradients.csproj
  MagicGradients/Parser/CssGradientParser.cs
  MagicGradients/Parser/TokenDefinitions/ColorChannelDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorHexDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorNameDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ITokenDefinition.cs
  MagicGradients/Parser/TokenDefinitions/LinearGradientDefinition.cs
  MagicGradients/RadialGradient.cs
  Playground/Playground.Android/Playground.Android.csproj
  Playground/Playground.iOS/Playground.iOS.csproj
  Playground/Playground/Models/Gradient.cs
  Playground/Playground/Playground.csproj
  Playground/Playground/Services/GalleryService.cs
  Playground/Playground/ViewModels/GalleryPreviewViewModel.cs
  Playground/Playground/ViewModels/PasteCssViewModel.cs
  Playground/Playground/Views/GalleryListPage.xaml
  Playground/Playground/Views/GalleryPreviewPage.xaml
  Playground/Playground/Views/InlineCssGradientPage.xaml
  Playground/Playground/Views/InlineGradientPage.xaml
  Playground/Playground/Views/PasteCssPage.xaml
  README.md
Labels: enhancement

#23 Radial gradients
  MagicGradients/Gradient.cs
  MagicGradients/GradientStop.cs
  MagicGradients/GradientView.cs
  MagicGradients/LinearGradient.cs
  MagicGradients/RadialGradient.cs
  MagicGradients/RadialGradientFlags.cs
  MagicGradients/Renderers/LinearGradientRenderer.cs
  MagicGradients/Renderers/RadialGradientRenderer.cs
  MagicGradients/Renderers/RenderContext.cs
  Playground/Playground/AppShell.xaml
  Playground/Playground/Playground.csproj
  Playground/Playground/Styles/LinearGradientsPage.css
  Playground/Playground/Views/LinearGradientsPage.xaml
  Playground/Playground/Views/LinearGradientsPage.xaml.cs
  Playground/Playground/Views/LinearGradientsPageCss.xaml
  Playground/Playground/Views/LinearGradientsPageCss.xaml.cs
  Playground/Playground/Views/RadialGradientsPage.xaml
  Playground/Playground/Views/RadialGradientsPage.xaml.cs
Labels: enhancement

#24 Support Repeating Linear Gradient
  MagicGradients.Tests/Parser/TokenDefinitions/ColorChannelDefinitionTests.cs
  MagicGradients/GradientBuilder.cs
  MagicGradients/LinearGradient.cs
  MagicGradients/Parser/CssToken.cs
  MagicGradients/Parser/CssTokenExtensions.cs
  MagicGradients/Parser/TokenDefinitions/ColorChannelDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorHexDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorNameDefinition.cs
  MagicGradients/Parser/TokenDefinitions/LinearGradientDefinition.cs
  MagicGradients/Renderers/LinearGradientRenderer.cs
  Playground/Playground/AppShell.xaml
  Playground/Playground/Playground.csproj
  Playground/Playground/Styles/RepeatingLinearGradientsPage.css
  Playground/Playground/Views/RepeatingLinearGradientsPage.xaml
  Playground/Playground/Views/RepeatingLinearGradientsPage.xaml.cs
  Playground/Playground/Views/RepeatingLinearGradientsPageCss.xaml
  Playground/Playground/Views/RepeatingLinearGradientsPageCss.xaml.cs
Labels: enhancement

#28 Fix small Typo
  README.md
Labels: documentation

#30 Support turn angle
  MagicGradients/Parser/CssReader.cs
  MagicGradients/Parser/TokenDefinitions/LinearGradientDefinition.cs
  MagicGradients/Parser/TokenDefinitions/RadialGradientDefinition.cs
  Playground/Playground/Views/GalleryListPage.xaml
  Playground/Playground/Views/GalleryListPage.xaml.cs
Labels: enhancement

#33 Playground adjustments
  Assets/Font/Read Me.txt
  Assets/Font/demo-files/demo.css
  Assets/Font/demo-files/demo.js
  Assets/Font/demo.html
  Assets/Font/fonts/icomoon.eot
  Assets/Font/fonts/icomoon.svg
  Assets/Font/fonts/icomoon.ttf
  Assets/Font/fonts/icomoon.woff
  Assets/Font/selection.json
  Assets/Font/style.css
  Playground/Playground.Android/Assets/icomoon.ttf
  Playground/Playground.Android/Playground.Android.csproj
  Playground/Playground.iOS/Playground.iOS.csproj
  Playground/Playground.iOS/Resources/icomoon.ttf
  Playground/Playground.iOS/Resources/tab_about.png
  Playground/Playground.iOS/Resources/tab_about@2x.png
  Playground/Playground.iOS/Resources/tab_about@3x.png
  Playground/Playground.iOS/Resources/tab_feed.png
  Playground/Playground.iOS/Resources/tab_feed@2x.png
  Playground/Playground.iOS/Resources/tab_feed@3x.png
  Playground/Playground.iOS/Resources/xamarin_logo.png
  Playground/Playground.iOS/Resources/xamarin_logo@2x.png
  Playground/Playground.iOS/Resources/xamarin_logo@3x.png
  Playground/Playground/App.xaml
  Playground/Playground/AppShell.xaml
  Playground/Playground/Constants/IconCodes.cs
  Playground/Playground/Playground.csproj
  Playground/Playground/Styles/Styles.xaml
Labels: enhancement

#39 Enhance gallery examples
  Playground/Playground/Constants/Category.cs
  Playground/Playground/Playground.csproj
  Playground/Playground/StaticData/Gradients/Angular.txt
  Playground/Playground/StaticData/Gradients/Burst.txt
  Playground/Playground/StaticData/Gradients/Checkered.txt
  Playground/Playground/StaticData/Gradients/Retro.txt
  Playground/Playground/StaticData/Gradients/Standard.txt
  Playground/Playground/StaticData/Gradients/Stripes.txt
  Playground/Playground/ViewModels/GalleryListViewModel.cs
Labels: enhancement

#42 Convert txt gradients to json
  MagicGradients.sln
  Playground/Playground.Data/Infrastructure/DatabaseProvider.cs
  Playground/Playground.Data/Infrastructure/IDatabaseProvider.cs
  Playground/Playground.Data/Models/Gradient.cs
  Playground/Playground.Data/Playground.Data.csproj
  Playground/Playground.Data/Repositories/DocumentRepository.cs
  Playground/Playground.Data/Repositories/GradientRepository.cs
  Playground/Playground.Data/Repositories/IDocumentRepository.cs
  Playground/Playground.Data/Repositories/IGradientRepository.cs
  Playground/Playground.Data/Resources/Angular.json
  Playground/Playground.Data/Resources/Burst.json
  Playground/Playground.Data/Resources/Checkered.json
  Playground/Playground.Data/Resources/Retro.json
  Playground/Playground.Data/Resources/Standard.json
  Playground/Playground.Data/Resources/Stripes.json
  Playground/Playground/App.xaml.cs
  Playground/Playground/IoC.cs
  Playground/Playground/Models/Gradient.cs
  Playground/Playground/Playground.csproj
  Playground/Playground/Properties/AssemblyInfo.cs
  Playground/Playground/Services/GalleryService.cs
  Playground/Playground/Services/IGalleryService.cs
  Playground/Playground/StaticData/Gradients/Angular.txt
  Playground/Playground/StaticData/Gradients/Burst.txt
  Playground/Playground/StaticData/Gradients/Checkered.txt
  Playground/Playground/StaticData/Gradients/Retro.txt
  Playground/Playground/StaticData/Gradients/Standard.txt
  Playground/Playground/StaticData/Gradients/Stripes.txt
  Playground/Playground/StaticData/StaticDataReader.cs
  Playground/Playground/ViewModels/GalleryListViewModel.cs
  Playground/Playground/ViewModels/GalleryPreviewViewModel.cs
Labels: enhancement

#43 Open in paste css
  Assets/Font/demo.html
  Assets/Font/fonts/icomoon.eot
  Assets/Font/fonts/icomoon.svg
  Assets/Font/fonts/icomoon.ttf
  Assets/Font/fonts/icomoon.woff
  Assets/Font/selection.json
  Assets/Font/style.css
  Playground/Playground.Android/Assets/icomoon.ttf
  Playground/Playground.iOS/Resources/icomoon.ttf
  Playground/Playground/AppShell.xaml
  Playground/Playground/AppShell.xaml.cs
  Playground/Playground/Constants/IconCodes.cs
  Playground/Playground/ViewModels/GalleryPreviewViewModel.cs
  Playground/Playground/ViewModels/PasteCssViewModel.cs
  Playground/Playground/ViewModels/ViewModelLocator.cs
  Playground/Playground/Views/GalleryPreviewPage.xaml
  Playground/Playground/Views/PasteCssPage.xaml
Labels: enhancement
