Repository mgierlasinski/MagicGradients, pull requests merged in 2020-04, with the labels that each got.

#70 Fixed Repeating Linear Gradients
  MagicGradients/Renderers/LinearGradientRenderer.cs
  Playground/Playground.Android/Resources/Resource.designer.cs
Labels: bug

#69 Feature #68 New Playground Page for Battle Test Gradients
  Assets/Font/demo-files/demo.css
  Assets/Font/demo.html
  Assets/Font/fonts/icomoon.eot
  Assets/Font/fonts/icomoon.svg
  Assets/Font/fonts/icomoon.ttf
  Assets/Font/fonts/icomoon.woff
  Assets/Font/selection.json
  Assets/Font/style.css
  Playground/Playground.Android/Assets/icomoon.ttf
  Playground/Playground.Android/Resources/Resource.designer.cs
  Playground/Playground.iOS/Resources/icomoon.ttf
  Playground/Playground/AppShell.xaml.cs
  Playground/Playground/Constants/IconCodes.cs
  Playground/Playground/IoC.cs
  Playground/Playground/Models/BattleItem.cs
  Playground/Playground/Playground.csproj
  Playground/Playground/Services/BattleItemService.cs
  Playground/Playground/Services/IPickerColorsDataProvider.cs
  Playground/Playground/Services/PickerColorsDataProvider.cs
  Playground/Playground/ViewModels/BattleTestViewModel.cs
  Playground/Playground/ViewModels/GalleryPreviewViewModel.cs
  Playground/Playground/ViewModels/PasteCssViewModel.cs
  Playground/Playground/ViewModels/ViewModelLocator.cs
  Playground/Playground/Views/BattleTestPage.xaml
  Playground/Playground/Views/BattleTestPage.xaml.cs
  Playground/Playground/Views/GalleryPreviewPage.xaml
Labels: enhancement, playground, 🛑 do not merge

#78 Add radial color picker for selecting themes
  MagicGradients.Library.slnf
  MagicGradients.Playground.slnf
  MagicGradients.PlaygroundLite.slnf
  MagicGradients.sln
  MagicGradients/LinearGradient.cs
  Playground/Playground.Android/Resources/Resource.designer.cs
  Playground/Playground.sln
  Playground/Playground/Controls/RadialMenu.xaml
  Playground/Playground/Controls/RadialMenu.xaml.cs
  Playground/Playground/Controls/RadialMenuCircle.cs
  Playground/Playground/Controls/RadialMenuItem.cs
  Playground/Playground/Models/GradientTheme.cs
  Playground/Playground/Playground.csproj
  Playground/Playground/Services/CategoryService.cs
  Playground/Playground/ViewModels/GalleryListViewModel.cs
  Playground/Playground/Views/GalleryListPage.xaml
Labels: enhancement
