Repository mgierlasinski/MagicGradients, pull requests merged in 2020-06, with the labels that each got.

#87 #86 Fix Icons & Fix Shadows at Battle Test View
  MagicGradients.sln
  Playground/Playground.Android/Assets/AboutAssets.txt
  Playground/Playground.Android/Playground.Android.csproj
  Playground/Playground.Android/Resources/Resource.designer.cs
  Playground/Playground.Data/Playground.Data.csproj
  Playground/Playground.iOS/Playground.iOS.csproj
  Playground/Playground.iOS/Resources/icomoon.ttf
  Playground/Playground/AppShell.xaml
  Playground/Playground/Controls/RadialMenu.xaml
  Playground/Playground/Playground.csproj
  Playground/Playground/Properties/AssemblyInfo.cs
  Playground/Playground/Resources/Fonts/icomoon.ttf
  Playground/Playground/Styles/Styles.xaml
  Playground/Playground/Views/BattleTestPage.xaml
  Playground/Playground/Views/GalleryListPage.xaml
  Playground/Playground/Views/GalleryPreviewPage.xaml
  Playground/Playground/Views/PasteCssPage.xaml
  PlaygroundLite/PlaygroundLite.Android/PlaygroundLite.Android.csproj
  PlaygroundLite/PlaygroundLite.Android/Properties/AndroidManifest.xml
  PlaygroundLite/PlaygroundLite.Android/Resources/Resource.designer.cs
  PlaygroundLite/PlaygroundLite.iOS/PlaygroundLite.iOS.csproj
  PlaygroundLite/PlaygroundLite/PlaygroundLite.csproj
Labels: bug, playground

#90 Fix parsing for angle "0" (no suffix)
  MagicGradients.Tests/Parser/TokenDefinitions/LinearGradientDefinitionTests.cs
  MagicGradients/Parser/TokenDefinitions/LinearGradientDefinition.cs
Labels: bug

#91 Change offset to struct
  MagicGradients.Tests/GradientTests.cs
  MagicGradients.Tests/Mock/MockApplication.cs
  MagicGradients.Tests/Mock/MockDeserializer.cs
  MagicGradients.Tests/Mock/MockPlatformServices.cs
  MagicGradients.Tests/Mock/MockResourcesProvider.cs
  MagicGradients.Tests/Mock/MockTicker.cs
  MagicGradients.Tests/OffsetTests.cs
  MagicGradients.Tests/OffsetTypeConverterTests.cs
  MagicGradients.Tests/Parser/CssGradientParserTests.cs
  MagicGradients.Tests/Parser/CssGradientParserTestsData.cs
  MagicGradients.Tests/Parser/CssTokenExtensionsTests.cs
  MagicGradients.Tests/Parser/GradientsComplex.cs
  MagicGradients.Tests/Parser/GradientsSimple.cs
  MagicGradients.Tests/Parser/GradientsWithoutOffsets.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorChannelDefinitionData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorChannelDefinitionTests.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorChannelDefinitionTestsData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorHexDefinitionData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorHexDefinitionTests.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorHexDefinitionTestsData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorNameDefinitionData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorNameDefinitionTests.cs
  MagicGradients.Tests/Parser/TokenDefinitions/ColorNameDefinitionTestsData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/LinearGradientDefinitionData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/LinearGradientDefinitionTests.cs
  MagicGradients.Tests/Parser/TokenDefinitions/LinearGradientDefinitionTestsData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/RadialGradientDefinitionData.cs
  MagicGradients.Tests/Parser/TokenDefinitions/RadialGradientDefinitionTests.cs
  MagicGradients.Tests/StringExtensionsTests.cs
  MagicGradients/Gradient.cs
  MagicGradients/GradientBuilder.cs
  MagicGradients/GradientMath.cs
  MagicGradients/GradientStop.cs
  MagicGradients/LinearGradient.cs
  MagicGradients/Offset.cs
  MagicGradients/OffsetTypeConverter.cs
  MagicGradients/Parser/CssHelpers.cs
  MagicGradients/Parser/CssTokenExtensions.cs
  MagicGradients/Parser/TokenDefinitions/ColorChannelDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorHexDefinition.cs
  MagicGradients/Parser/TokenDefinitions/ColorNameDefinition.cs
  MagicGradients/Parser/TokenDefinitions/LinearGradientDefinition.cs
  MagicGradients/Parser/TokenDefinitions/RadialGradientDefinition.cs
  MagicGradients/Parser/Vector2.cs
  MagicGradients/RadialGradient.cs
  MagicGradients/RadialGradientEnums.cs
  MagicGradients/RadialGradientFlags.cs
  MagicGradients/RadialGradientShape.cs
  MagicGradients/StringExtensions.cs
  Playground/Playground.Android/Resources/Resource.designer.cs
  Playground/Playground/Models/GradientEditorItem.cs
  Playground/Playground/Views/LinearGradientsAnimationPage.xaml.cs
Labels: enhancement

#83 New Gradients Database
  Playground/Playground.Android/MainActivity.cs
  Playground/Playground.Android/Resources/Resource.designer.cs
  Playground/Playground.Data/Playground.Data.csproj
  Playground/Playground.Data/Resources/Angular.json
  Playground/Playground.Data/Resources/BackGammon.json
  Playground/Playground.Data/Resources/BasicGrid.json
  Playground/Playground.Data/Resources/Burst.json
  Playground/Playground.Data/Resources/Categories.json
  Playground/Playground.Data/Resources/Checkered.json
  Playground/Playground.Data/Resources/ComplexCircles.json
  Playground/Playground.Data/Resources/ComplexGrid.json
  Playground/Playground.Data/Resources/ComplexPatterns.json
  Playground/Playground.Data/Resources/ComplexRepStripes.json
  Playground/Playground.Data/Resources/ComplexShapes.json
  Playground/Playground.Data/Resources/DarkBg.json
  Playground/Playground.Data/Resources/Diamond.json
  Playground/Playground.Data/Resources/Fracture.json
  Playground/Playground.Data/Resources/FutureStripes.json
  Playground/Playground.Data/Resources/Gingham.json
  Playground/Playground.Data/Resources/GinghamColored.json
  Playground/Playground.Data/Resources/LightBg.json
  Playground/Playground.Data/Resources/Metadata.json
  Playground/Playground.Data/Resources/RadialStripes.json
  Playground/Playground.Data/Resources/RainbowStandard.json
  Playground/Playground.Data/Resources/RepStripes.json
  Playground/Playground.Data/Resources/Retro.json
  Playground/Playground.Data/Resources/SimpleAngular.json
  Playground/Playground.Data/Resources/SimpleCircles.json
  Playground/Playground.Data/Resources/SimplePatterns.json
  Playground/Playground.Data/Resources/Standard.json
  Playground/Playground.Data/Resources/StandardAsymmetrical.json
  Playground/Playground.Data/Resources/StandardCircle.json
  Playground/Playground.Data/Resources/Stripes.json
Labels: enhancement
